- name: Start fabric operations
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Show the role
      debug:
        msg: 'Running BUILD'

    - name: Show the parameters
      debug:
        msg: '{{ CHAINCODE_SOURCE_DIR }}  {{ CHAINCODE_METADATA_DIR }}  {{ BUILD_OUTPUT_DIR }}'
