- name: Start fabric operations
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Show the role
      debug:
        msg: 'Running DETECT'

    - name: Load metadata.json
      set_fact:
        cmetadata: "{{ lookup('file', CHAINCODE_METADATA_DIR + '/metadata.json') | from_json }}"

    - name: Verify the metadata label
      fail:
        msg: "The chaincode metadata label must be provided"
      when: cmetadata.label == ''

    - name: Verify the metadata path
      fail:
        msg: "The chaincode metadata path must be provided"
      when: cmetadata.path == ''