---
# perform an action

- name: Prepare for the action
  set_fact:
    agentworkdir: "{{ workdir }}/{{ action.aworkdir }}"

- name: Make sure that the work directory is clean
  file:
    path: '{{ agentworkdir }}'
    state: '{{ item }}'
  with_items:
  - absent
  - directory

- name: "Start action {{ action.name }}"
  debug:
    var: action.parameters

- name: Execute the action
  include_tasks: '{{ role_path }}/ops/{{ action.name }}/apply.yml'

- name: Post action
  debug:
    msg: 'Action {{ action.name }} is now finished'