---
# perform an action

- name: Prepare for the action
  set_fact:
    agentworkdir: "{{ workdir }}/{{ action.aworkdir }}"

- name: Make sure that the work directory is clean
  file:
    path: '{{ agentworkdir }}'
    state: '{{ item }}'
  with_items:
  - absent
  - directory

- name: "Start action {{ action.name }}"
  debug:
    var: action.parameters

- name: Execute the action
  include_tasks: '{{ role_path }}/ops/{{ action.name }}/apply.yml'

# Wait for the action to be completed regardles successful or not
- name: Wait for the action to complete
  community.kubernetes.k8s_info:
    kind: Agent
    api_version: 'operator.fabric.hyperledger.org/v1alpha1'
    name: '{{ ansible_operator_meta.name }}'
    namespace: '{{ ansible_operator_meta.namespace }}'
    wait: yes
    wait_timeout: 300
    wait_condition:
      type: Running
      status: "True"
