- name: Make sure that working directory exists
  file:
    path: '{{ workdir }}'
    state: 'directory'
    mode: 0775

- name: Check if the binary already exists
  stat:
    path: '{{ bindir }}/bin/peer'
  register: binflag

- name: Get binary when it does not exist
  when: not binflag.stat.exists
  block:
  - name: Get the tar file
    get_url:
      url: https://github.com/hyperledger/fabric/releases/download/v2.3.2/hyperledger-fabric-linux-amd64-2.3.2.tar.gz
      dest: '{{ bindir }}'

  - name: Unpackage the tar file
    unarchive:
      src: '{{ bindir }}/hyperledger-fabric-linux-amd64-2.3.2.tar.gz'
      dest: '{{ bindir }}'
      creates: '{{ bindir }}/bin/peer'