---
# tasks file for Agent
- name: Validate configurations
  include_tasks: 'validation.yml'

- name: Get binary
  include_tasks: 'get-fabric-bin.yml'

- name: Execute the action
  include_tasks: '{{ role_path }}/ops/{{ action.name }}/apply.yml'
  loop: '{{ actions }}'
  loop_control:
    loop_var: action