---
# tasks file for Agent
- name: Validate configurations
  include_tasks: 'validation.yml'

- name: Get binary
  include_tasks: 'get-fabric-bin.yml'

- name: Execute the action
  include_tasks: 'doaction.yml'
  loop: '{{ tactions }}'
  loop_control:
    loop_var: action