---
# tasks file for Agent
- name: Validate configurations
  include_tasks: 'validation.yml'

- name: Get binary
  include_tasks: 'get-fabric-bin.yml'

- name: Execute the action
  include_tasks: 'doaction.yml'
  loop: '{{ tactions }}'
  loop_control:
    loop_var: action

- name: Make sure that the work directory is clean
  when: cleanup == True
  file:
    path: '{{ workdir }}'
    state: 'absent'
