- name: Check if the organization variable is set
  fail:
    msg: "organization must be provided in the request"
  when: organization == None or (organization|trim) == ''

- name: Check if the agent type is set and valid
  fail:
    msg: "agent type must be provided and be admin or user"
  when: type == None or (type|trim) == '' or ((type|lower) not in ('admin', 'user'))

- name: Get all the actions
  set_fact:
    allactions: '{{ actions | map(attribute="name") | list }}'

- name: Get available actions
  find:
    paths: '{{ role_path }}/ops'
    recurse: no
    file_type: directory
  register: availableactions_var

- name: Get supported actions
  set_fact:
    supactions: "{{ availableactions_var.files | map(attribute='path') | list | map('basename') | list }}"

- name: Validate all actions must be part of supported
  fail:
    msg: 'Action {{ allactions | difference(supactions) | join(",") }} not supported!'
  when: (allactions | difference(supactions) | length) > 0

- name: Set work directory
  set_fact:
    bindir: "{{ lookup('env','HOME') }}/agent/{{ release }}"
    workdir: "{{ lookup('env','HOME') }}/agent/{{ 99999999 | random | to_uuid }}"
    orgid: "{{ organization | replace('.', '-') }}"

- name: Setup action working directory
  set_fact:
    tactions: >-
      {{ tactions|default([]) +
         [ item | combine({'aworkdir':((item|to_nice_json|hash('sha256')))[:16]}) ] }}
  with_items: "{{ actions }}"

- debug:
    var: tactions