- name: Make sure that asset target directory exists
  file:
    path: '{{ item }}'
    state: 'directory'
    mode: 0775
  with_items:
  - '{{ agentworkdir }}/assets'
  - '{{ agentworkdir }}/assets/Ordering_Services'
  - '{{ agentworkdir }}/assets/Wallets'

- name: Setup the file name
  set_fact:
    assetname: "{{ anode.metadata.name }}-{{ anode.spec.organization | replace('.', '-') }}"

- name: Retrieve the node cert secret
  community.kubernetes.k8s_info:
    kind: Secret
    api_version: v1
    name: "{{ assetname }}-nodecert"
    namespace: '{{ ansible_operator_meta.namespace }}'
  register: thesecret

- name: Now generate the Orderer asset for organization
  template:
    src: "{{ role_path }}/ops/{{ action.name }}/templates/orderer.j2"
    dest: "{{ agentworkdir }}/assets/Ordering_Services/{{ assetname }}.json"

- name: Now generate the msp asset for organization
  template:
    src: "{{ role_path }}/ops/{{ action.name }}/templates/wallet.j2"
    dest: "{{ agentworkdir }}/assets/Wallets/Admin-{{ assetname }}.json"
  when: includewallets == True
