apiVersion: operator.fabric.hyperledger.org/v1alpha1
kind: Agent
metadata:
  name: agent-channel-create
spec:
  organization: example.com
  actions:
  - name: channelcreate
    description: Create new channel
    parameters:
      channelName: mychannel1
      ordererNode: orderer1-example-com
      additionalOrgs:
      - org0ca1-org0-example-com
      - org1ca1-org1-example-com
