apiVersion: operator.fabric.hyperledger.org/v1alpha1
kind: Agent
metadata:
  name: agent-channel-query
spec:
  organization: example.com
  nodeCert: admin1
  actions:
  - name: channelquery
    description: query channel configuration
    parameters:
      channelName: mychannel
      ordererNode: orderer1-example-com