apiVersion: operator.fabric.hyperledger.org/v1alpha1
kind: Agent
metadata:
  name: agent-sample
spec:
  organization: example.com
  actions:
  - name: nodeimport
    description: import nodes and their certificates
    parameters:
      assetname: assets.zip
