---
apiVersion: operator.fabric.hyperledger.org/v1alpha1
kind: Orderer
metadata:
  name: orderer1
spec:
  # Add fields here
  organization: example.com
  nodeCert:
  release: 2.3.2
  storage: 1Gi
  logLevel: DEBUG