---
collections:
  - name: community.kubernetes
    version: "2.0.0"
  - name: operator_sdk.util
    version: "0.4.0"
  - name: community.general
    version: "5.5.0"
  - name: community.crypto
    version: "2.5.0"