- name: Start fabric operations
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - name: test
    set_fact:
      myvar: "{{ range(0, 3) | list }}"

  - name: Load the configuration file
    include_vars:
      file: "molecule/production/.org1.yml"



  - debug:
      msg: "{{ namespace }}"