- name: Start fabric operations
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - set_fact:
      ab: 'aaa'

  - debug:
      var: ab

  - name: test
    set_fact:
      myvar: "{{ range(0, 3) | list }}"
      legacy: "{{ ab is defined and ab != None and ab != '' }}"


  - debug:
      var: legacy