- name: Start fabric operations
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - name: Check if this is k8s
      set_fact:
        used_ports: "{{ [4, 5, 6, 8, 10] }}"
        ext_port: 4

    - name: find an available port
      set_fact:
        ext_port: "{{ item }}"
      when: ext_port in used_ports
      loop: "{{ range(4, 500, 1) | list }}"
      
    - get_url:
        url: https://github.com/hyperledger/fabric/releases/download/v2.3.2/hyperledger-fabric-linux-amd64-2.3.2.tar.gz
        dest: /opt/ansible

    - unarchive:
        src: /opt/ansible/hyperledger-fabric-linux-amd64-2.3.2.tar.gz
        dest: /opt/ansible/bin
        creates: /opt/ansible/bin/bin/peer
