- name: Start fabric operations
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  - name: setup variable
    set_fact:
      downloadurl: "kubectl cp -n osdk-test -c manager osdk-controller-manager-64fb694b5b-qglqj:/opt/ansible/agent/download/mychannel_config.json"

  - set_fact:
      nodecertname: >-
        {{ ( (node_cert is not defined) or (node_cert == None) or ((node_cert|trim) == '') ) 
          | ternary('The default value', node_cert) }}

  - debug:
      var: nodecertname