---
# This module basically setup various ca, orderer, peer nodes for
# an organization.
- name: Set up loop control variables
  set_fact:
    resstate: "{{ state|default('present') }}"
    allnodes: >-
      {{ [{'type': 'ca', 'no': number_of_ca, 'prefix': ca_prefix},
          {'type': 'orderer', 'no': number_of_orderer|default(0), 'prefix': orderer_prefix},
          {'type': 'orderer_legacy', 'no': number_of_orderer_legacy|default(0), 'prefix': orderer_prefix},
          {'type':'peer', 'no': number_of_peer, 'prefix': peer_prefix} ] }}

- name: Create ca, orderer, peer node based on configuration
  include_tasks: 'processnodes.yml'
  loop: "{{ allnodes }}"
  loop_control:
    loop_var: fabricnode

