- name: Process nodes
  community.kubernetes.k8s:
    state: "{{ resstate }}"
    namespace: '{{ namespace }}'
    definition: >-
      {{ lookup('template', '/'.join([project_dir,
        'molecule/basesystem/tasks/templates', fabricnode.type+'.j2'])) | from_yaml }}
    wait: yes
    wait_timeout: 300
    wait_condition:
      type: Running
      reason: Successful
      status: "True"
  loop: "{{ range(0, fabricnode.no) | list }}"
  loop_control:
    loop_var: nodeindex

- name: Process nodes
  when: resstate == 'present'
  community.kubernetes.k8s_info:
    kind: Pod
    name: "{{ fabricnode.prefix }}-{{ nodeindex }}-0"
    namespace: '{{ namespace }}'
    wait: yes
    wait_sleep: 10
    wait_timeout: 60
    wait_condition:
      type: Ready
      status: "True"
  loop: "{{ range(0, fabricnode.no) | list }}"
  loop_control:
    loop_var: nodeindex
