apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
      - args:
        - --leader-elect
        - --leader-election-id=fabric-operator
        image: controller:latest
        imagePullPolicy: IfNotPresent
        name: manager
        env:
        - name: ANSIBLE_GATHERING
          value: explicit
        - name: ANSIBLE_VERBOSITY_CA_OPERATOR_FABRIC_HYPERLEDGER_ORG
          value: "0"
        - name: ANSIBLE_VERBOSITY_ORDERER_OPERATOR_FABRIC_HYPERLEDGER_ORG
          value: "0"
        - name: ANSIBLE_VERBOSITY_PEER_OPERATOR_FABRIC_HYPERLEDGER_ORG
          value: "0"
        - name: ANSIBLE_VERBOSITY_NODECERT_OPERATOR_FABRIC_HYPERLEDGER_ORG
          value: "0"
        - name: ANSIBLE_VERBOSITY_AGENT_OPERATOR_FABRIC_HYPERLEDGER_ORG
          value: "0"
        - name: ANSIBLE_VERBOSITY_CONSOLE_OPERATOR_FABRIC_HYPERLEDGER_ORG
          value: "0"
        - name: MAX_CONCURRENT_RECONCILES_CA_OPERATOR_FABRIC_HYPERLEDGER_ORG
          value: "1"
        - name: MAX_CONCURRENT_RECONCILES_ORDERER_OPERATOR_FABRIC_HYPERLEDGER_ORG
          value: "1"
        - name: MAX_CONCURRENT_RECONCILES_PEER_OPERATOR_FABRIC_HYPERLEDGER_ORG
          value: "1"
        - name: MAX_CONCURRENT_RECONCILES_NODECERT_OPERATOR_FABRIC_HYPERLEDGER_ORG
          value: "1"
        - name: MAX_CONCURRENT_RECONCILES_AGENT_OPERATOR_FABRIC_HYPERLEDGER_ORG
          value: "1"
        - name: MAX_CONCURRENT_RECONCILES_CONSOLE_OPERATOR_FABRIC_HYPERLEDGER_ORG
          value: "1"
        securityContext:
          allowPrivilegeEscalation: false
        livenessProbe:
          httpGet:
            path: /healthz
            port: 6789
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 6789
          initialDelaySeconds: 5
          periodSeconds: 10
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
