---
- name: Create the operator.fabric.hyperledger.org/v1alpha1.Nodecert
  community.kubernetes.k8s:
    state: present
    namespace: '{{ namespace }}'
    definition: "{{ lookup('template', '/'.join([samples_dir, cr_file])) | from_yaml }}"
    wait: yes
    wait_timeout: 300
    wait_condition:
      type: Running
      reason: Successful
      status: "True"
  vars:
    cr_file: 'operator_v1alpha1_nodecert.yaml'
  register: cmdresult

- name: Check the resource
  assert:
    that:
    - cmdresult.failed == False
    - cmdresult.changed == True
    - cmdresult.method == 'create'
    - cmdresult.result.status.conditions[0].ansibleResult.failures == 0
    fail_msg: Fabric Node cert creation failed
    success_msg: Fabric Node cert creation succeeded
