---
- name: Create the operator.fabric.hyperledger.org/v1alpha1.Peer
  k8s:
    state: present
    namespace: '{{ namespace }}'
    definition: "{{ lookup('template', '/'.join([samples_dir, cr_file])) | from_yaml }}"
    wait: yes
    wait_timeout: 300
    wait_condition:
      type: Running
      reason: Successful
      status: "True"
  vars:
    cr_file: 'operator_v1alpha1_peer.yaml'
  register: cmdresult

- name: Check the resource
  assert:
    that:
    - cmdresult.failed == False
    - cmdresult.changed == True
    - cmdresult.method == 'create'
    - cmdresult.result.status.conditions[0].ansibleResult.failures == 0
    - cmdresult.result.status.operations != ''
    - cmdresult.result.status.endpoint != ''
    fail_msg: Fabric Peer node creation failed
    success_msg: Fabric Peer node creation succeeded

- name: Access the operation endpoint
  get_url:
    url: "{{ cmdresult.result.status.operations }}/healthz"
    dest: /tmp/notimportant
  register: cmdresult

- name: Check the response
  assert:
    that:
    - cmdresult.status_code == 200
    fail_msg: Fabric Peer node healthz check failed
    success_msg: Fabric Peer node healthz check succeeded
