# To create a new channel, an action must look like this
#
# spec:
#   organization: example.com
#   actions:
#   - name: channeljoin
#     description: join a peer to the channel
#     parameters:
#       channelName: mychannel
#       ordererNode: orderer-sample-example-com
#       peerNode: peer-sample-example-com

- name: Show the passed in variable
  debug:
    var: action

- name: Get variable with their names
  set_fact:
    channelName: "{{ action.parameters.channel_name }}"
    ordererNode: "{{ action.parameters.orderer_node }}"
    peerNode: "{{ action.parameters.peer_node }}"

- name: End the process if either variable is empty
  when: channelName == '' or ordererNode == '' or peerNode == ''
  include_tasks: '{{ ROOTDIR }}/playbooks/common/endplay.yml'
  vars:
    RESULT_MSG: 'Failed - Channel name, orderer node, peer node all must be provided'

- name: Mark the start of the agent
  include_tasks: '{{ ROOTDIR }}/playbooks/common/startplay.yml'
  vars:
    KIND: Agent

# Now we get the orderer node info from either nodecert or node asset
- name: Get orderer node info
  include_tasks: '{{ ROOTDIR }}/playbooks/common/getnodeinfo.yml'
  vars:
    thesecretname: "{{ ordererNode }}"
    targetdir: "{{ agentworkdir }}"

- name: Get orderer node admin endpoint
  set_fact:
    ordererid: "{{ lookup('file', agentworkdir+'/'+ordererNode+'/msp/id.json') | from_json }}"

- name: Get peer node info
  include_tasks: '{{ ROOTDIR }}/playbooks/common/getnodeinfo.yml'
  vars:
    thesecretname: "{{ peerNode }}"
    targetdir: "{{ agentworkdir }}"

- name: Get peer node admin endpoint
  set_fact:
    peerid: "{{ lookup('file', agentworkdir+'/'+peerNode+'/msp/id.json') | from_json }}"

- name: Get core yaml files
  copy:
    src: '{{ bindir }}/config'
    dest: '{{ agentworkdir }}' 

# When we reach here, we should have either the orderer node cert or
# orderer node asset secret. Here the orderer node is used as peer
# credential (msp) contains the actual user msp information. This is
# extremely confusing.
- name: 'Query channel {{ channelName }}'
  ansible.builtin.shell: |
    export FABRIC_CFG_PATH={{ agentworkdir }}/config
    export CORE_PEER_TLS_ENABLED=true
    export CORE_PEER_LOCALMSPID={{ peerid.mspid }}
    export CORE_PEER_TLS_ROOTCERT_FILE={{ agentworkdir }}/{{ peerNode }}/tls/ca.crt
    export CORE_PEER_MSPCONFIGPATH={{ agentworkdir }}/{{ peerNode }}/msp
    export CORE_PEER_ADDRESS={{ peerid.endpoint }}
    {{ bindir }}/bin/peer channel fetch oldest config_block.bk \
    --tls -c {{ channelName }} -o {{ ordererid.endpoint }} \
    --cafile {{ agentworkdir }}/{{ ordererNode }}/tls/ca.crt --connTimeout 120s
  args:
    chdir: '{{ agentworkdir }}'
    executable: /bin/bash
  register: cmdresult
  ignore_errors: yes

- name: Update the resource status
  when: cmdresult.rc != 0
  include_tasks: '{{ ROOTDIR }}/playbooks/common/endplay.yml'
  vars:
    RESULT_MSG: "Failed - {{ cmdresult.stderr }}"

- name: 'Join the peer to the channel {{ channelName }}'
  ansible.builtin.shell: |
    export FABRIC_CFG_PATH={{ agentworkdir }}/config
    export CORE_PEER_TLS_ENABLED=true
    export CORE_PEER_LOCALMSPID={{ peerid.mspid }}
    export CORE_PEER_TLS_ROOTCERT_FILE={{ agentworkdir }}/{{ peerNode }}/tls/ca.crt
    export CORE_PEER_MSPCONFIGPATH={{ agentworkdir }}/{{ peerNode }}/msp
    export CORE_PEER_ADDRESS={{ peerid.endpoint }}
    {{ bindir }}/bin/peer channel join -b config_block.bk \
    --tls -o {{ ordererid.endpoint }} \
    --cafile {{ agentworkdir }}/{{ ordererNode }}/tls/ca.crt --connTimeout 120s
  args:
    chdir: '{{ agentworkdir }}'
    executable: /bin/bash
  register: cmdresult
  ignore_errors: yes

- name: Update the resource status
  include_tasks: '{{ ROOTDIR }}/playbooks/common/endplay.yml'
  vars:
    RESULT_MSG: >-
      {{ (cmdresult.rc == 0)|ternary('Succeeded - Channel join',
         'Failed - Channel Join. '+cmdresult.stderr ) }}
