# To create a new channel, an action must look like this
#
# - name: channeljoin
#   description: join a channel
#   params:
#   - name: channelName
#     value: mychannel
#   - name: node
#     value: peer-sample
#
# The node parameter indicates the peer node and its secret has to
# be available on the cluster.

- name: Show the passed in variable
  debug:
    var: action

