---
# The tasks to remove port from istio
- name: Get the gateway info
  community.kubernetes.k8s_info:
    name: '{{ ansible_operator_meta.name }}-gateway'
    namespace: '{{ ansible_operator_meta.namespace }}'
    api_version: 'networking.istio.io/v1beta1'
    kind: Gateway
  register: thegateway

- name: Search for all istio ingress gateway deployment
  community.kubernetes.k8s_info:
    kind: 'Service'
    label_selectors:
      - app = istio-ingressgateway
      - istio = ingressgateway
      - release = istio
      - operator.istio.io/component = IngressGateways
  register: istio_svc

- name: Search for all istio ingress gateway deployment
  community.kubernetes.k8s_info:
    kind: 'Deployment'
    label_selectors:
      - app = istio-ingressgateway
      - istio = ingressgateway
      - release = istio
      - operator.istio.io/component = IngressGateways
  register: istio_dep

- name: Remove the port from istio system
  when: ((thegateway.resources|length) == 1) and ((istio_dep.resources|length) == 1) and ((istio_svc.resources|length) == 1)
  community.kubernetes.k8s:
    definition: "{{ lookup('template', 'templates/'+item+'_del.j2')|from_yaml }}"
  with_items:
  - service
  - deployment
