- name: Process nodes
  community.kubernetes.k8s:
    state: "{{ resstate }}"
    namespace: '{{ namespace }}'
    definition: >-
      {{ lookup('template', '/'.join([project_dir,
        'molecule/fabricorg/templates', fabricnode.type+'.j2'])) | from_yaml }}
    wait: yes
    wait_timeout: 300
    wait_condition:
      type: Running
      reason: Successful
      status: "True"
  loop: "{{ range(0, fabricnode.no) | list }}"
  loop_control:
    loop_var: nodeindex
