- name: Start fabric operations
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
    - get_url:
        url: "https://github.com/hyperledger/fabric/releases/download/v{{ RELEASE }}/hyperledger-fabric-linux-amd64-{{ RELEASE }}.tar.gz"
        dest: '/var/hyperledger/production/fabricbin.tar.gz'

    - unarchive:
        src: '/var/hyperledger/production/fabricbin.tar.gz'
        dest: '/var/hyperledger/production'
        mode: 'u+x'
        group: '1001'
        owner: '1001'

    - name: Copy peer to right place
      copy:
        src: '/var/hyperledger/production/bin/peer'
        dest: '/var/hyperledger/production/peer'

    - name: Load the core yaml file
      set_fact:
        coreyaml: "{{ lookup('file', '/var/hyperledger/production/config/core.yaml') | from_yaml }}"
        extbuilders: "{{ {'externalBuilders':[
          {'name': 'k8schaincode', 'path': '/opt/ansible/launcher', 'propagateEnvironment': [
            'KUBERNETES_SERVICE_HOST', 'KUBERNETES_SERVICE_PORT','PEER_OPERATOR_NAME',
            'PEER_OPERATOR_ORG', 'CORE_PEER_MSPCONFIGPATH', 'CORE_PEER_LOCALMSPID',
            'CORE_PEER_ID', 'FABRIC_CFG_PATH', 'HOME', 'CORE_PEER_TLS_ENABLED',
            'CORE_PEER_TLS_CERT_FILE', 'CORE_PEER_TLS_KEY_FILE', 'CORE_PEER_TLS_ROOTCERT_FILE'
          ]}
        ] } }}"

    - name: Get chaincode settings together
      set_fact:
        chaincodesetting: "{{ coreyaml.chaincode | combine(extbuilders) }}"

    - name: Add the external chaincode builder to the core
      set_fact:
        coreyaml: "{{ coreyaml | combine({'chaincode': chaincodesetting}) }}"

    - name: Copy core.yaml to right place
      copy:
        dest: '/var/hyperledger/production/core.yaml'
        content: >-
          {{ coreyaml | to_nice_yaml(indent=2) }}
