# permissions for end users to view chaincodes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: chaincode-viewer-role
rules:
- apiGroups:
  - operator.fabric.hyperledger.org
  resources:
  - chaincodes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.fabric.hyperledger.org
  resources:
  - chaincodes/status
  verbs:
  - get
