# permissions for end users to view nodecerts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodecert-viewer-role
rules:
- apiGroups:
  - operator.fabric.hyperledger.org
  resources:
  - nodecerts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.fabric.hyperledger.org
  resources:
  - nodecerts/status
  verbs:
  - get
