# permissions for end users to edit peers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: peer-editor-role
rules:
- apiGroups:
  - operator.fabric.hyperledger.org
  resources:
  - peers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.fabric.hyperledger.org
  resources:
  - peers/status
  verbs:
  - get
