---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
    resources:
      - secrets
      - pods
      - pods/exec
      - pods/log
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - namespaces
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for istio resources.
  ##
  - apiGroups:
      - networking.istio.io
    resources:
      - gateways
      - virtualservices
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for operator.fabric.hyperledger.org/v1alpha1, Kind: Orderer
  ##
  - apiGroups:
      - operator.fabric.hyperledger.org
    resources:
      - orderers
      - orderers/status
      - orderers/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for operator.fabric.hyperledger.org/v1alpha1, Kind: CA
  ##
  - apiGroups:
      - operator.fabric.hyperledger.org
    resources:
      - cas
      - cas/status
      - cas/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for operator.fabric.hyperledger.org/v1alpha1, Kind: Peer
  ##
  - apiGroups:
      - operator.fabric.hyperledger.org
    resources:
      - peers
      - peers/status
      - peers/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for operator.fabric.hyperledger.org/v1alpha1, Kind: Nodecert
  ##
  - apiGroups:
      - operator.fabric.hyperledger.org
    resources:
      - nodecerts
      - nodecerts/status
      - nodecerts/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for operator.fabric.hyperledger.org/v1alpha1, Kind: Agent
  ##
  - apiGroups:
      - operator.fabric.hyperledger.org
    resources:
      - agents
      - agents/status
      - agents/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for operator.fabric.hyperledger.org/v1alpha1, Kind: Chaincode
  ##
  - apiGroups:
      - operator.fabric.hyperledger.org
    resources:
      - chaincodes
      - chaincodes/status
      - chaincodes/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  ##
  ## Rules for operator.fabric.hyperledger.org/v1alpha1, Kind: Console
  ##
  - apiGroups:
      - operator.fabric.hyperledger.org
    resources:
      - consoles
      - consoles/status
      - consoles/finalizers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
#+kubebuilder:scaffold:rules
