- name: Check if the organization variable is set
  fail:
    msg: "organization must be provided in the request"
  when: organization == None or (organization|trim) == ''

- name: Setup project root path
  set_fact:
    ROOTDIR: "{{ lookup('env','HOME') }}"