---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: no

  tasks:
    - name: Build operator image
      command: make docker-build -IMG={{ operator_image }}
      args:
        chdir: '{{ project_dir }}'

    - name: Load image into kind cluster
      command: kind load docker-image --name osdk-test '{{ operator_image }}'
      register: result
      changed_when: '"not yet present" in result.stdout'

- import_playbook: ../default/converge.yml
