---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
  - name: Use the tools script to setup k8s
    command: "{{ project_dir }}/tools/nginxk8s.sh"

  - name: Set pull policy
    command: '{{ kustomize }} edit {{ item.action }} patch pull_policy/{{ item.policy }}.yaml'
    args:
      chdir: '{{ config_dir }}/testing'
    with_items:
    - { 'action': 'remove', 'policy': 'Always' }
    - { 'action': 'remove', 'policy': 'IfNotPresent' }
    - { 'action': 'remove', 'policy': 'Never' }
    - { 'action': 'add', 'policy': '{{ operator_pull_policy }}' }

