apiVersion: operator.fabric.hyperledger.org/v1alpha1
kind: CA
metadata:
  name: ca-sample
spec:
  # Add fields here
  organization: example.com
  certs: ca-sample-example-com-certs
  admin: ca-sample-example-com-admin