apiVersion: operator.fabric.hyperledger.org/v1alpha1
kind: Agent
metadata:
  name: agent-sample
spec:
  organization: example.com
  cleanup: true
  actions:
  - name: assetgen
    description: Generate asset file
    parameters:
      assettypes: ['ca', 'orderer', 'peer']
      channelName: 'mychannel'
      includewallets: no
