apiVersion: operator.fabric.hyperledger.org/v1alpha1
kind: Agent
metadata:
  name: agent-sample
spec:
  organization: example.com
  actions:
  - name: legacychannelcreate
    description: Create new channel
    parameters:
      channelName: mychannel
      ordererNode: orderer-sample-example-com
      additionalOrgs: []
