apiVersion: operator.fabric.hyperledger.org/v1alpha1
kind: Agent
metadata:
  name: agent-sample
spec:
  organization: example.com
  nodeCert: admin01-sample
  actions:
  - name: orgjoin
    description: query channel configuration
    parameters:
      channelName: mychannel
      orderer: orderer-sample
      newOrgAdminNodeCert: admin01-sample-org0-example-com-nodecert
