apiVersion: operator.fabric.hyperledger.org/v1alpha1
kind: Agent
metadata:
  name: agent-sample
spec:
  organization: example.com
  nodeCert: admin01-sample
  actions:
  - name: channelquery
    description: query channel configuration
    parameters:
      channelName: mychannel
      ordererNode: orderer-sample-example-com