apiVersion: operator.fabric.hyperledger.org/v1alpha1
kind: Agent
metadata:
  name: agent-sample
spec:
  organization: example.com
  actions:
  - name: channeljoin
    description: join a peer to the channel
    parameters:
      channelName: mychannel
      ordererNode: orderer-sample-example-com
      peerNode: peer-sample-example-com