---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    # - name: Create test kind cluster
    #   command: kind create cluster --name osdk-test --kubeconfig {{ kubeconfig }}
    - name: Use the tools script to setup k8s
      command: "{{ project_dir }}/tools/nginxk8s.sh --name osdk-test --kubeconfig {{ kubeconfig }}"

    - name: Build operator image
      command: make docker-build -IMG={{ operator_image }}
      args:
        chdir: '{{ project_dir }}'

    - name: Load image into kind cluster
      command: kind load docker-image --name osdk-test '{{ operator_image }}'
      register: result
      changed_when: '"not yet present" in result.stdout'

    - name: Create Namespace
      community.kubernetes.k8s:
        api_version: v1
        kind: Namespace
        name: '{{ namespace }}'
        kubeconfig: '{{ kubeconfig }}'

    - import_tasks: ../default/kustomize.yml
      vars:
        state: present
