# This module update the resource with start status
# Do this when we start a resource

- name: Update resource status
  operator_sdk.util.k8s_status:
    api_version: operator.fabric.hyperledger.org/v1alpha1
    kind: "{{ KIND | default('Agent') }}"
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    status:
      download: ""
      upload: ""
      result: ""
    conditions:
      - type: Running
        status: "False"
        reason: "Running"
        message: "{{ KIND | default('Agent') | title }} is starting"
        lastTransitionTime: "{{ lookup('pipe', 'date --rfc-3339 seconds') }}"

