---
- name: Converge
  hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - community.kubernetes

  tasks:
    - name: Create Namespace
      k8s:
        api_version: v1
        kind: Namespace
        name: '{{ namespace }}'
        kubeconfig: '{{ kubeconfig }}'

    - import_tasks: kustomize.yml
      vars:
        state: present

    - import_tasks: tasks/ca_test.yml
      vars:
        state: present