- name: Check if the organization variable is set
  fail:
    msg: "organization must be provided in the request"
  when: organization == None or (organization|trim) == ''

- name: Check if the node type is set and valid
  fail:
    msg: "node type must be provided and be one of CA, Orderer, Peer, Console, Admin or User in the request"
  when: node_type == None or (node_type|trim) == '' or ((node_type|lower) not in ('ca', 'orderer', 'peer', 'console', 'admin', 'user'))

- name: Set mspid and work directory
  set_fact:
    mspid: "{{ ansible_operator_meta.name }}-{{ organization|replace('.', '-') }}"
    workdir: "{{ lookup('env','HOME') }}/vars"
