- name: Make sure that binary directory exists
  file:
    path: '{{ item }}'
    state: 'directory'
    mode: 0775
  with_items:
  - '{{ bindir }}'
  - '{{ workdir }}'

- name: Check if the binary already exists
  stat:
    path: '{{ bindir }}/bin/peer'
  register: binflag

- name: Get binary when it does not exist
  when: not binflag.stat.exists
  block:
  - name: Get the tar file
    get_url:
      url: 'https://github.com/hyperledger/fabric/releases/download/v{{ release }}/hyperledger-fabric-linux-amd64-{{ release }}.tar.gz'
      dest: '{{ bindir }}/fabricbin.tar.gz'

  - name: Unpackage the tar file
    unarchive:
      src: '{{ bindir }}/fabricbin.tar.gz'
      dest: '{{ bindir }}'

  - name: Remove the tar gz file since it is no longer needed
    file:
      path: '{{ bindir }}/fabricbin.tar.gz'
      state: 'absent'

- name: Get core yaml files
  copy:
    src: '{{ bindir }}/config'
    dest: '{{ workdir }}'
