# To import external nodes into your clusters
#
# spec:
#   organization: example.com
#   actions:
#   - name: channelsignoff
#     description: sign off channel configuration changes
#     parameters:
#       envelopeFile: mychannel_update_envelope.pb
#       channelName: mychannel
#       ordererNode: orderer-sample-example-com
#       peerNode: peer-sample-example-com
#
# envelopeFile indicate the desired channel configuration which must be
# a full channel configuration json file. This file has to be uploaded
# to the agent first
#
# channelName is the channel name which will be updated.
#
# ordererNode is the orderer node used to send channel changes to.
# this node can be an imported node, only needs its endpoint and
# ca tls cert.
#
# peerNode is the peer node under which credential that the changes
# will be made. It has to be a full node with all the signing and
# private key certs available.

- name: Show the passed in variable
  debug:
    var: action

- name: Get variable with their names
  set_fact:
    envelopeFile: "{{ action.parameters.envelope_file }}"
    channelName: "{{ action.parameters.channel_name }}"
    ordererNode: "{{ action.parameters.orderer_node }}"
    peerNode: "{{ action.parameters.peer_node }}"

- name: End the process if asset name was not provided
  when: envelopeFile == ''
  include_tasks: '{{ role_path }}/common/endplay.yml'
  vars:
    RESULT_MSG: 'Failed - the envelope file must be provided for signing off'

- name: Check if the envelope file exists
  stat:
    path: '{{ uploaddir }}/{{ envelopeFile }}'
  register: configfile

- name: End the process when envelope file does not exist
  when: not configfile.stat.exists
  include_tasks: '{{ role_path }}/common/endplay.yml'
  vars:
    RESULT_MSG: 'Failed - envelope file {{ envelopeFile }} must be uploaded for signing'

- name: Mark the start of the agent
  include_tasks: '{{ role_path }}/common/startplay.yml'

- name: Get envelope file
  copy:
    src: '{{ uploaddir }}/{{ envelopeFile }}'
    dest: '{{ agentworkdir }}/{{ channelName }}_update_envelope.pb' 

# Now we get the orderer node info from either nodecert or node asset
- name: Get orderer node info
  include_tasks: '{{ role_path }}/common/getnodeinfo.yml'
  vars:
    thesecretname: "{{ ordererNode }}"

- name: Get orderer node admin endpoint
  set_fact:
    ordererid: "{{ lookup('file', agentworkdir+'/'+ordererNode+'/msp/id.json') | from_json }}"

- name: Get peer node info
  include_tasks: '{{ role_path }}/common/getnodeinfo.yml'
  vars:
    thesecretname: "{{ peerNode }}"

- name: Get peer node admin endpoint
  set_fact:
    peerid: "{{ lookup('file', agentworkdir+'/'+peerNode+'/msp/id.json') | from_json }}"

- name: Get core yaml files
  copy:
    src: '{{ bindir }}/config'
    dest: '{{ agentworkdir }}'

- name: Generate the signoff script
  template:
    src: "{{ role_path }}/ops/channelsignoff/templates/process.j2"
    dest: "{{ agentworkdir }}/process.sh"
    mode: +x

- name: Sign off the changes
  ansible.builtin.command: "{{ agentworkdir }}/process.sh"
  args:
    chdir: '{{ agentworkdir }}'
  register: cmdresult
  ignore_errors: yes

- name: Update the resource status
  when: cmdresult.rc != 0
  include_tasks: '{{ role_path }}/common/endplay.yml'
  vars:
    RESULT_MSG: 'Failed - Channel Signoff. {{ cmdresult.stderr}}'

- name: Update the resource status
  include_tasks: '{{ role_path }}/common/endplay.yml'
  vars:
    RESULT_MSG: 'Succeeded - Channel Signoff'
    DOWNLOAD_MSG: >-
      kubectl cp -n {{ controllerns }} -c manager {{ podname }}:{{ downloaddir }}/{{ channelName }}_update_envelope.pb
