# This module update the agent status with 3 parameters
#   RESULT_MSG
#   DOWNLOAD_MSG
#   UPLOAD_MSG
# If DOWNLOAD_MSG or UPLOAD_MSG is not provided, empty value
# is assume. If RESULT_MSG is not provide, Succeeded is assumed

- name: Set success or fail flag
  set_fact:
    OK: "{{ RESULT_MSG is regex('^Succeeded*') }}"

- name: Update agent status
  operator_sdk.util.k8s_status:
    api_version: operator.fabric.hyperledger.org/v1alpha1
    kind: Agent
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    status:
      download: "{{ DOWNLOAD_MSG | default('') }}"
      upload: "{{ UPLOADLOAD_MSG | default('') }}"
      result: "{{ RESULT_MSG }}"
    conditions:
      - type: Running
        status: "True"
        reason: "{{ OK | ternary('Successful', 'Failed') }}"
        lastTransitionTime: "{{ lookup('pipe', 'date --rfc-3339 seconds') }}"

- name: End the whole process if the msg is not Succeeded
  when: not OK
  meta: end_play
