# This module query installed chaincode
# required parameters are
#    1. must be called from agent
#    2. peer node info
#    3. fabric config directory is set at the agentworkdir/config
#    4. chaincode label
- name: Query chaincode
  ansible.builtin.shell: |
    set -e
    export FABRIC_CFG_PATH={{ agentworkdir }}/config
    export FABRIC_LOGGING_SPEC=ERROR
    export CORE_PEER_TLS_ENABLED=true
    export CORE_PEER_LOCALMSPID={{ peerid.mspid }}
    export CORE_PEER_TLS_ROOTCERT_FILE={{ agentworkdir }}/{{ peerNode }}/tls/ca.crt
    export CORE_PEER_MSPCONFIGPATH={{ agentworkdir }}/{{ peerNode }}/msp
    export CORE_PEER_ADDRESS={{ peerid.endpoint }}
    {{ bindir }}/bin/peer lifecycle chaincode queryinstalled -O json | tee out.json
  args:
    chdir: '{{ agentworkdir }}'
    executable: /bin/bash
  register: cmdresult
  ignore_errors: yes

- name: Load the json file
  set_fact:
    installed: "{{ lookup('file', agentworkdir+'/out.json') | from_json }}"

- name: Find the target chaincode
  set_fact:
    thetarget: >
      {{ installed.installed_chaincodes | default([]) | selectattr('label', 'equalto', cclabel) | list }}

- set_fact:
    ccid: "{{ (thetarget|length == 0)|ternary('', thetarget[0].package_id) }}"

- when: channelName is defined and channelName != ''
  set_fact:
    refid: >-
      {{ (thetarget|length == 0)|ternary('',
        (thetarget[0].references|default({channelName: ''}))[channelName] ) }}