# This module update the agent with start status
# Do this when we start a resource

- name: Update agent status
  operator_sdk.util.k8s_status:
    api_version: operator.fabric.hyperledger.org/v1alpha1
    kind: Agent
    name: "{{ ansible_operator_meta.name }}"
    namespace: "{{ ansible_operator_meta.namespace }}"
    status:
      download: ""
      upload: ""
    conditions:
      - type: Running
        status: "Running"
        reason: "Running"
        message: "Agent is starting"
        lastTransitionTime: "{{ lookup('pipe', 'date --rfc-3339 seconds') }}"

