orgname: "org1.example.com"
ca_prefix: "org1ca"
number_of_ca: 1
orderer_prefix: "org1orderer"
number_of_orderer: 1
peer_prefix: "org1peer"
number_of_peer: 1
orderernode: "org1orderer-0-org1-example-com"
peernode: "org1peer-0-org1-example-com"
agentname: "org1agent"
namespace: "org1space"