- name: Load the configuration file
  include_vars:
    file: ".org{{ seq }}.yml"

- include_tasks: ../basesystem/tasks/orgs.yml
  vars:
    state: absent

- name: Remove the agent
  community.kubernetes.k8s:
    state: "absent"
    namespace: '{{ namespace }}'
    definition: >-
      {{ lookup('template', project_dir+'/molecule/basesystem/tasks/templates/agent_assetgen.j2') | from_yaml }}
    wait: yes

- name: Remove the namespace
  community.kubernetes.k8s:
    api_version: v1
    kind: Namespace
    name: '{{ namespace }}'
    kubeconfig: '{{ kubeconfig }}'
    state: absent

