# update istio service to support new tcp port
- name: Update istio ingress gateway service and its deployment
  when: ext_port > 0
  block:
  - name: Adding the port to istio ingress service
    community.kubernetes.k8s:
      name: '{{ istio_service_name }}'
      namespace: '{{ istio_namespace }}'
      api_version: v1
      kind: Service
      merge_type: strategic-merge
      definition:
        spec:
          ports:
          - name: "tcp{{ ext_port }}"
            port: "{{ ext_port }}"
            protocol: TCP
            targetPort: "{{ ext_port }}"
  
  # Update istio deployment with the new port
  - name: Adding the port to istio ingress deployment
    community.kubernetes.k8s:
      name: '{{ istio_deplyment_name }}'
      namespace: '{{ istio_namespace }}'
      api_version: v1
      kind: Deployment
      merge_type: strategic-merge
      definition:
        spec:
          template:
            spec:
              containers:
              - name: istio-proxy
                ports:
                - containerPort: "{{ ext_port }}"
                  protocol: TCP
