---
- name: Update istio system
  hosts: localhost
  gather_facts: no
  connection: local
  tasks:
  # The tasks to remove ports
  - name: Get istio information
    include_tasks: "get-istio-info.yaml"
  
  - name: Get the gateway info
    community.kubernetes.k8s_info:
      name: '{{ ansible_operator_meta.name }}-gateway'
      namespace: '{{ ansible_operator_meta.namespace }}'
      api_version: 'networking.istio.io/v1beta1'
      kind: Gateway
    register: thegateway
  
  - name: Remove the port from istio system
    when: (thegateway.resources|length) == 1
    community.kubernetes.k8s:
      definition: "{{ lookup('template', 'templates/'+item+'_del.j2')|from_yaml }}"
    with_items:
    - service
    - deployment

  - name: Remove the persistent volume claims when the resource is CA
    block:
    - name: Get the pvcs
      community.kubernetes.k8s_info:
        api_version: v1
        kind: PersistentVolumeClaim
        namespace: "{{ ansible_operator_meta.namespace }}"
      register: pvc_info
  
    - set_fact:
        pvc_name: "{{ ansible_operator_meta.name }}-{{ organization|replace('.', '-') }}"
  
    - name: Delete all the pvcs
      community.kubernetes.k8s:
        state: absent
        api_version: "{{ item.apiVersion }}"
        kind: "{{ item.kind }}"
        name: "{{ item.metadata.name }}"
        namespace: "{{ item.metadata.namespace }}"
      when: item.metadata.labels['k8s-app'] == pvc_name
      with_items: "{{ pvc_info.resources }}"