---
- name: Create
  hosts: localhost
  connection: local
  gather_facts: false
  tasks: []
    - name: Set pull policy
      command: '{{ kustomize }} edit add patch pull_policy/{{ operator_pull_policy }}.yaml'
      args:
        chdir: '{{ config_dir }}/testing'
